CREATE TABLE [Core].[CustomerInformation]
(
	[Id] INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	[CustomerInformationId] UNIQUEIDENTIFIER NOT NULL,
	[Email] NVARCHAR(100) NOT NULL,
	[PhoneNumber] NVARCHAR(100) NOT NULL,
	[Data] VARCHAR(MAX) NOT NULL
)
GO

CREATE UNIQUE INDEX [IX_CUSTOMERINFORMATION_CUSTOMERINFORMATIONID] ON [Core].[CustomerInformation]([CustomerInformationId])
GO
CREATE INDEX [IX_CUSTOMERINFORMATION_EMAIL] ON [Core].[CustomerInformation]([Email])
GO
CREATE INDEX [IX_CUSTOMERINFORMATION_PHONENUMBER] ON [Core].[CustomerInformation]([PhoneNumber])
GO