CREATE TABLE [Core].[Inquiries]
(
	[Id] INT IDENTITY(1,1) NOT NULL PRIMARY KEY, 
    [InquiryId] UNIQUEIDENTIFIER NOT NULL, 
    [InquiryNumber] INT NULL,
    [CreatedByClientId] UNIQUEIDENTIFIER NOT NULL, 
    [InquiryState] INT NOT NULL, 
    [CustomerEmail] NVARCHAR(100) NULL, 
    [UserId] UNIQUEIDENTIFIER NULL,
    [Data] VARCHAR(MAX) NOT NULL
)
GO

CREATE UNIQUE INDEX [IX_INQUIRIES_INQUIRYID] ON [Core].[Inquiries]([InquiryId])
GO
CREATE INDEX [IX_INQUIRIES_CREATEDBYCLIENTID] ON [Core].[Inquiries]([CreatedByClientId])
GO
CREATE INDEX [IX_INQUIRIES_USERID] ON [Core].[Inquiries]([UserId])
GO
CREATE INDEX [IX_INQUIRIES_CUSTOMEREMAIL] ON [Core].[Inquiries]([CustomerEmail])
GO
CREATE INDEX [IX_INQUIRIES_INQUIRYSTATE] ON [Core].[Inquiries]([InquiryState])
GO
CREATE INDEX [IX_INQUIRIES_INQUIRYNUMBER] ON [Core].[Inquiries]([InquiryNumber])
GO