CREATE TABLE [Core].[Products]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY(1,1), 
    [Guid] UNIQUEIDENTIFIER NOT NULL,
    [Price] INT NOT NULL, 
    [IsActive] BIT NOT NULL, 
    [Category] NVARCHAR(50) NOT NULL, 
    [Name] NVARCHAR(200) NOT NULL, 
    [Data] NVARCHAR(MAX) NOT NULL
)
GO

CREATE UNIQUE INDEX [IX_PRODUCTS_GUID] ON [Core].[Products]([Guid])
GO
CREATE INDEX [IX_PRODUCTS_CATEGORY] ON [Core].[Products]([Category])
GO
CREATE INDEX [IX_PRODUCTS_TITLE] ON [Core].[Products]([Name])
GO