CREATE TABLE [dbo].[Users]
(
	[Id] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY, 
    [Username] NVARCHAR(1000) NOT NULL DEFAULT '', 
    [Email] NVARCHAR(1000) NOT NULL, 
    [Data] NVARCHAR(MAX) NOT NULL 
)
GO

CREATE INDEX IX_USERS_USERNAME ON Users(Username)
GO
CREATE INDEX IX_USERS_EMAIL ON Users(Email)